### ISSUE TITLE
Manager does not close.  Lingers in background?

### ISSUE THREAD

**Issue by DeFlight** [hawkeye-stan/msfs-popout-panel-manager#117] opened 2024-04-30 21:15 UTC
I am noticing something rather interesting.  it would appear Pop out manager does not close completely.  It lingers as I go to task manager and it is still there.  Furthermore, it causes me to not be able to reload MSFS as it thinks MSFS is still running for something.  I use the steam version.  I notice also if I just normally close it, the auto pop out happens anyway unless I go to task manager and completely end the task.  thanks!

**Comment by hawkeye-stan** [comment] 2024-05-01 15:37
I'm not able to reproduce your issue. By any chance you have POPM minimize to tray instead of closing the app. In any case, I'll continue to try to see what could be causing your problem.

**Comment by DeFlight** [comment] 2024-05-01 15:44
I do have it mimize to tray.  However, when I close the app the icon is gone and the app is still lingering in the background.  In any event, I do notice, when it is running normally and I close MSFS it still will not close MSFS properly.  I am wondering if I should delete all your files and then reload them?

**Comment by DeFlight** [comment] 2024-05-01 16:59
So, I dont have anything loaded or running.  I just opened your program, works, then close it.  Still lingers on Task manager.  No icon anywhere.  Also, I want to uninstall everything but I notice the "settings" linger.  Where is the files to remove?  I looked through program data and app data and can not find anything.

**Comment by DeFlight** [comment] 2024-05-02 15:49
I am curious if it has something to do with One Drive then.  I have my 2 computers sharing the documents folder.  I am going to remove the folder and then try and see.  What can I do, if anything, to give you more information to figure out what is causing this?

**Comment by hawkeye-stan** [comment] 2024-05-04 22:23
Not sure could One Drive causing POPM to hang since my system is not setup with One Drive as documents folder. A to-do on my list is to add alternate folder support where POPM's data files are stored.

**Comment by SierraBravo1** [comment] 2024-06-01 23:37
I had the same issue.
First I reset all my settings by deleting appsettingdata.json in the documents folder -> The issue was gone.
After that, I tested in detail which setting prevents the correct termination of the program -> It is Keyboard Shortcuts.
**Keyboard Shortcuts must be enabled.** If I disable it, POPM does not close completely.

**Comment by hawkeye-stan** [comment] 2024-06-04 13:47
[SierraBravo1](https://github.com/SierraBravo1)
Thanks for the information. I'm looking into the issue. POPM could be constantly trying to detect keyboard input in the background which causes the app fail to close properly.

**Comment by hawkeye-stan** [comment] 2024-06-15 02:11
I've tried various scenarios but was unable to reproduce the issue either with keyboard shortcut preference setting active or inactive. It must be something else on certain PC that causes POPM to not be able to close correctly.

**Comment by DeFlight** [comment] 2024-07-01 20:21
I have been so busy I have not even opened MSFS in a month or 2.  When I do I will see if this issue continues as I am reinstalling MSFS and pop up

**Comment by mdenadal** [comment] 2024-07-20 05:42
I confirm this issue, same behaviour as reported  by @DeFlight 
I confirm @hawkeye-stan 's workaround too. 
Keeping "Keyboard Shortcuts" active (even with no "Keyboard Binding" assigned) prevents the problem.

**Comment by hawkeye-stan** [comment] 2024-07-26 15:59
I've identified the issue that causes inability for POPM to close correctly. A fix will be released before end of July. Thank you all for helping in narrowing down the issue about "Keyboard Shortcuts".

**Comment by hawkeye-stan** [comment] 2024-07-28 00:44
Version 4.1.1 has been released and hopefully it fixes this issue.

**Comment by mdenadal** [comment] 2024-07-28 12:29
I confirm 4.1.1 fixes the problem (at least on my system).

**Closed** 2024-07-31 17:10 UTC

**Comment by SierraBravo1** [comment] 2024-07-31 19:49
fixed, thank you
