### ISSUE TITLE
Popout fails after 3.4.3 update

### ISSUE THREAD

**Issue by Narvik-Ramius** [hawkeye-stan/msfs-popout-panel-manager#40] opened 2022-09-12 19:18 UTC
Hi, I use since a few weeks/month a profile to export 4 displays for the FENIX A320 to an external mini-monitor. All was still working fine yesterday.

Today, after automatic 3.4.3 update, the popout process fails.

The first two displays (PFD - ND) are exported, but the process fails for the third screen (upper ecam) and stops here.

However, the panel location overlay is ok, there's no obstruction, and I can (manually) export the display. 
![image](https://user-images.githubusercontent.com/76492436/189737114-ece57eab-a217-4ac5-8e72-e9eb3442399e.png)

The error I get is : "Unable to pop out panel number 3. Please check panel's number circle is positioned inside the panel, check for panel obstruction, and check if panel can be popped out. Pop out process stopped."

**Comment by hawkeye-stan** [comment] 2022-09-12 21:11
Hi Narvik-Ramius,

I sorry that you're having an issue with the latest version 3.4.3. I tried to reproduce your issue on a standard A320 and FlyByWire A320 but was unable to reproduce it. Unfortunately, I don't have FENIX A320 to test with and I'm not sure what could be causing your issue at the moment. 

You can roll back to previous version of the application by downloading release v3.4.2 and just replace "MSFSPopoutPanelManager.exe" in the installation folder. When you start the app and is asked to update, just click skip update.

https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/tag/v3.4.2

In the mean time, I'll dive into my code and see what could be causing your issue and I will also report back if I receive similar report from other users.

Stanley

**Comment by hawkeye-stan** [comment] 2022-09-12 21:51
Hi Narvik-Ramius,

After looking at my code, the only change in my app that could be causing your issue is I've updated the UI to display the number circle momentarily before a panel is being popped out. I'm guessing in your case, the number circle display somehow is blocking the actual Right Alt / Left Click keystroke to pop out the panel. I've added a small delay between the number circle display and the actual sending of the pop out keystroke and it may fix your issue. If you don't mind, please download the following test release build "msfs-popout-panel-manager-fenix-a320-fix-test.zip" from the link below. You can extract it and replace the files in your POPM installed folder. All your user profile settings will not be affected.

https://github.com/hawkeye-stan/debug-and-support/releases/tag/POPM-Fenix-A320-Fix-Test

If the fix doesn't work, you can still roll back to previous v3.4.2 which was working for you. If this does work, please report back and I will create a hot fix to release to users who may have encountered this particular issue on their Fenix A320.

Thanks,
Stanley

**Comment by Narvik-Ramius** [comment] 2022-09-13 05:25
Hi Stanley, thanks for your replies. I downloaded the fix you mentionned, but with no effect on the problem.

I reverted to 3.4.2 and everything went fine again.

The problem doesn't seem to occur when the screen is popped out, but just after that, when the third screen is "separated" from the popped out window. In case that might help you, I recorded two videos : one with 3.4.2 and one with 3.4.3.

v3.4.2 (works fine) : https://youtu.be/Fx4naYv4fno

v3.4.3 (problem appears) : https://youtu.be/SnAwbmv3wV8 

In case that might help, the panels locations and settings are: 
![image](https://user-images.githubusercontent.com/76492436/189815859-da928ef4-80b9-4ba3-9f26-ad24576f8158.png)

And here is the .json config for this aircraft profile :

{"ProfileId":2,"ProfileName":"A320 FENIX","BindingAircrafts":["FNX320"],"PanelSourceCoordinates":[{"PanelIndex":1,"X":1812,"Y":1176},{"PanelIndex":2,"X":2359,"Y":1169},{"PanelIndex":3,"X":3296,"Y":1186},{"PanelIndex":4,"X":3283,"Y":1686}],"PanelConfigs":[{"PanelIndex":1,"PanelName":"Panel1","PanelType":2,"Top":2160,"Left":892,"Width":480,"Height":480,"AlwaysOnTop":true,"HideTitlebar":true,"FullScreen":false,"TouchEnabled":false,"DisableGameRefocus":false},{"PanelIndex":2,"PanelName":"Panel2","PanelType":2,"Top":2160,"Left":1371,"Width":480,"Height":480,"AlwaysOnTop":true,"HideTitlebar":true,"FullScreen":false,"TouchEnabled":false,"DisableGameRefocus":false},{"PanelIndex":3,"PanelName":"Panel3","PanelType":2,"Top":2160,"Left":1852,"Width":480,"Height":480,"AlwaysOnTop":true,"HideTitlebar":true,"FullScreen":false,"TouchEnabled":false,"DisableGameRefocus":false},{"PanelIndex":4,"PanelName":"Panel4","PanelType":2,"Top":2160,"Left":2333,"Width":480,"Height":480,"AlwaysOnTop":true,"HideTitlebar":true,"FullScreen":false,"TouchEnabled":false,"DisableGameRefocus":false}],"TouchPanelBindings":[],"BindingAircraftLiveries":[],"IsLocked":false,"PowerOnRequiredForColdStart":false,"IncludeInGamePanels":false,"MsfsGameWindowConfig":{"Top":0,"Left":0,"Width":0,"Height":0}}

**Comment by hawkeye-stan** [comment] 2022-09-13 13:06
Hi Narvik-Ramius,

Thanks for the video. Looks like something is off with Windows OS display scale or coordinates after the first panel is popped out. In your video, the momentary display of number circles were elongated. I will look at the issue when I get home tonight and see what's going on. Hopefully, I can identify the cause and provide you a fix for your issue.

Stanley

**Comment by eyablonowitz** [comment] 2022-09-15 04:03
I am a new user of both the Fenix A320 and msfs-popout-panel-manager.  I can report a similar issue.  I say similar because it differs from the original report  in two respects:
1.  I always get an error on panel 2 rather than 3.  It doesn't matter what panel I select as panel 2 or the order.
2. I can reproduce the issue with 3.4.2 as well as 3.4.3.

As with the original report, the issue seems to occur not at pop-out time but when the panel-manager attempts to separate the second panel from the first.  Selecting a single panel also works fine which further adds to my confidence the issue is related to the separation not the initial pop-out.

**Comment by eyablonowitz** [comment] 2022-09-15 04:47
Got a screenshot of the separation.  Looks like it may be clicking the wrong button?
<img width="976" alt="image" src="https://user-images.githubusercontent.com/18173536/190316855-fb25535a-e425-48d8-9863-e8b2a99bf167.png">

**Comment by hawkeye-stan** [comment] 2022-09-15 16:52
Hi eyablonowitz,

Thanks for the screenshot and it really helps me identify the problem. It looks like an issue with my app not getting the correct coordinates to click to separate the panel in rare configuration (such as in your Fenix A320). In the screenshot, when the "merged" left and right panel have very different scale (the right one is almost twice as wide than the left one), MSFS will scale them in a way that my app's calculated "estimate" coordinate about where to click is off. The higher resolution the monitor display, the less accurate it gets because the target header button area is so small. 

I'll definitively look into this issue and implement more accurate way to find the header button to click and will release a fix ASAP.

As for a possible workaround in the meantime, if you make the panel on the left in your screenshot (the narrower one) as the last selection, it may be able to fix your issue?

Stanley

**Comment by hawkeye-stan** [comment] 2022-09-15 17:58
Hi Narvik-Ramius, the issue that eyablonowitz is having maybe the same as yours. Hopefully, once I implement a fix, it will solve your issue also.

Stanley

**Comment by eyablonowitz** [comment] 2022-09-15 20:07
Thanks Stanley.  Does this snip give you what you what you are looking for?
![image](https://user-images.githubusercontent.com/18173536/190498824-c59b9b0f-8c8f-4930-bdf2-277158d5d692.png)

**Comment by hawkeye-stan** [comment] 2022-09-15 20:12
This is perfect. I will try my best to figure out the issue and code a fix for you.

Stanley

**Comment by eyablonowitz** [comment] 2022-09-15 20:14
Actually realized the last capture was from a lower resolution that I tried as an attempt to workaround the issue.  Not sure if it matters but here is an equiv at my normal 4K resolution.
![image](https://user-images.githubusercontent.com/18173536/190499936-3187d811-b5cf-40c1-9f79-ee1e51373329.png)

**Comment by fabianovm** [comment] 2022-09-23 08:56
Hello Stanley and friends! I´m trying to first create a profile to configure the 2 GTC´s - Garmin Touch controls on a Honda Jet, SU10, MSFS popout manager v3.4.3 and v3.4.2 also. No success. I experience same problems, when I select instrument 1 and 2, after that, click control+left mouse and for a few seconds a see both together in a msfs popout window but something happens, and i got the same error here reported "Unable to pop out panel #" and just one of the gtc stays on popped out windows. Tried to make it work for the whole night, no success, if you guys can help or need something from me in order to help, let me know!
![hjet gtcs](https://user-images.githubusercontent.com/86928223/191925376-86f82089-fd4a-4da9-9e5d-33a0fe5c51d5.png)

**Comment by hawkeye-stan** [comment] 2022-09-23 16:16
Hi all,

I think I've found the culprit of the problem. I believe the issue is the base pop out window title bar in Windows OS. In windows 10 or 11, I'm guessing with different windows theme or different window scale, the pop out window title bar (in Red) has much taller height than I expected. This in turn affect the calculation for MSFS instrumentation pop out title bar height (in Orange) which I used to determine the relative location of "magnifying glass" icon to click. I've changed the algorithm in how I get the MSFS instrumentation title bar height and it seems to make my calculation much more accurate. 

![image](https://user-images.githubusercontent.com/72271266/192005360-eedbde86-9450-4a74-8f74-4af1b7f06665.png)

Since I'm not able to reproduce your issues on my Windows 11 machine, I need your help and hope the following beta build will fix your issue. Please download the following zip file and unzip the exe in your installation folder and overwrite your v3.4.3 exe. All your settings and profile will not be affected. Also, if this works for you, you can continue using this version until I do an official v3.4.4 release and the app will automatically update for you at that time for any new additional feature.

https://github.com/hawkeye-stan/debug-and-support/releases/download/POPM-PopOutSeparationFix/MSFSPopoutPanelManager-beta-issue40.zip

If this fix does not work, you can revert back to v3.4.3 version by redownloading it from the release section in this repo and I'll go back to drawing board and see what else could be causing the problem.

Stanley

**Comment by Narvik-Ramius** [comment] 2022-09-23 17:19
Hi Stanly,

looks good !! Seems to work for me. I'll have to do more tests to be sure, but I tried two flight starts, and the popout process was fine both. Many thanks !

**Comment by fabianovm** [comment] 2022-09-23 18:44
Hi Stanley, I did a first quick test - have to get kids from school now - and it WORKED OK, on first attempt on HJET. Just the FPS drop was massive, from 57fps to 30fps for 3 instruments poped out. If you know any trick to reduce this impact, let me know please! Will do more tests today, with time,  and let you know in details, but yes, it seems you did the magic, thanks a lot!!!!!!!

**Comment by hawkeye-stan** [comment] 2022-09-23 19:20
Glad the fix seems to be working! 

As for pop out FPS drop, running the game with DX12 have no FPS penalty but if you're using Nvidia GPU, quite a few users have reported issue that the performance is not stable with current Nvidia driver in SU10. They're waiting for new GPU driver release in the next few days. As for AMD GPU which I have, DX12 runs almost as good as DX11 other than high VRAM usage in certain built-up area which could cause FPS drop. But when I need to fly VFR in the country or use pop out for an aircraft, I'll run the game in DX12.

**Comment by fabianovm** [comment] 2022-09-24 01:59
> Glad the fix seems to be working!
> 
> As for pop out FPS drop, running the game with DX12 have no FPS penalty but if you're using Nvidia GPU, quite a few users have reported issue that the performance is not stable with current Nvidia driver in SU10. They're waiting for new GPU driver release in the next few days. As for AMD GPU which I have, DX12 runs almost as good as DX11 other than high VRAM usage in certain built-up area which could cause FPS drop. But when I need to fly VFR in the country or use pop out for an aircraft, I'll run the game in DX12.

-->Exactly  what I was thinking ,  I´m on nvidia latest drivers dx11, think that the new driver and dx12 should help, because I know the FPS loss is on the msfs itself side, not on msfs popout manager side, it is beautiful now!! thanks a lot!!! will start the sim now, if I notice something else, let you know! have  a nice weekend! Thanks a lot Stanley!

**Comment by fabianovm** [comment] 2022-09-24 13:48
Good morning Stanley, just curious, how many VRAM you have in your GPU? Can you tell me the model just for comparision? thanks!

**Comment by hawkeye-stan** [comment] 2022-09-25 03:34
I've an AMD 5700XT with 8gb of VRAM

**Comment by fabianovm** [comment] 2022-09-25 16:25
Thanks for letting me know your VRAM, I have 10gb so it wold be ok with directx 12, like yours, thanks!

Bu the way, I used the msfs popout manager beta you sent me, for all day long yesterday and seems to work ok, did not see any problems on honda jet, thanks a lot!!!

**Comment by hawkeye-stan** [comment] 2022-09-28 18:29
This fix will officially integrate into upcoming release 3.4.4

**Comment by fabianovm** [comment] 2022-09-29 01:00
> This fix will officially integrate into upcoming release 3.4.4

Thank you very much Stanley, I tried today with DX12 and latest drivers, no fps loss with popup, as you said, but sadly I have to tune the configs because my vram is on  limit and the fps went below 30, 26, on landing, I will solve it soon!

best regards!

**Comment by hawkeye-stan** [comment] 2022-10-09 01:21
Fix has been implemented in v3.4.4 release.

**Closed by hawkeye-stan** 2022-10-09 01:21 UTC
