### ISSUE TITLE
Additional unconfigured panel pops out (Usually EFB, Multiple planes)

### ISSUE THREAD

**Issue by jopeek** [hawkeye-stan/msfs-popout-panel-manager#99] opened 2023-12-01 03:35 UTC
On the PMDG, when I have several popouts configured, the efb also pops out. In other planes it’s often the efb as well (FSR500, for example). On one of the FBW’s, it ended up popping out one of the MCP LCD displays (speed or course window).

any idea what’s going on? This impacts making popouts full screen as well which stops working. It seems to sometimes attach itself to what’s actually intended to be popped out. 

For example, in the FSR500, I specify the PFD and MFD to pop out. The PFD is fine but then the MFD pops out and with it comes the EFB. The title bar of the MFD window is NOT the custom name I entered but rather AS1000_MFD. The EFB popout title ends up being the one I specified in pppm.

**Comment by hawkeye-stan** [comment] 2023-12-05 17:53
Looks like this could be a bug in PMDG aircraft affecting some users. I'm not able to reproduce it even though I fly PMDG 737-800 80% of the time.

**Comment by jopeek** [comment] 2023-12-05 19:12
I would agree but it happens in other aircraft too. Including the fsr500 and 787-10. But it appears to be an MSFS bug as manually popping out a display will also sometimes do that.

Sent with Spark

**Comment by hawkeye-stan** [comment] 2023-12-06 21:23
This bug happened much more frequently for me more than a year ago, especially when I flew A320 and encountered this particular bug quite often (either using POPM or manual pop out). I remember if I restart the game, the bug disappear. I thought this bug was supposed to be resolved by Microsoft since I no longer have this error. But it looks like for certain machine, this issue is still happening and I'm not sure what exactly is the root cause. Since POPM emulates mouse click which performs mouse click much faster than a human can, and the mouse click executes some game code behind the scene, I believe this makes the bug surface itself more than manually popping out panel for certain machine. 

My setup for 737-800 with POPM auto pop out when flight start is:
- Popping out 5 panels including EFB 
- Windows 11, AMD 7800x3D CPU, Nvidia 4080, Microsoft Store version of the game
- POPM turbo mode enable which makes panel to pop out even faster

**Comment by Adi-18** [comment] 2023-12-31 18:26
Same here on FBW a320 neo. I Just wish pop out PFD and MFD, but also tablet will pop out.

![MSFSPopoutPanelManager_Wrong](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/29123730/a82a9503-af4f-4b70-af3d-5be299d882a5)

**Comment by jahlives** [comment] 2024-01-15 06:51
I have the same issue with PMDG 737 (using MSFS): if I want to popout MFD and/or PFD it always pop-out the PMDG tablet as well. And only the tablet is positioned according to the coordinates set in popout-panel-manager. MFD and/or PFD always got positioned in full screen on my most right display. Also if changing position via keys it only affects the tablet position/size. Is this a bug in PMDG or in popout-manager?

**Comment by hawkeye-stan** [comment] 2024-01-24 23:03
It could be a bug in PMDG since I've been flying 737 80% of the time and have POPM configured to pop out PFD/MFD/ECAM and POPM did not pop out the flight tablet screen.

**Closed** 2024-05-04 22:24 UTC
