### ISSUE TITLE
Stops on Panel #2

### ISSUE THREAD

**Issue by Maarp68** [hawkeye-stan/msfs-popout-panel-manager#50] opened 2022-12-04 03:33 UTC
Hi Stanley,

Thanks for this great utility, but I've had a problem lately. When start the popout (on 2 different aircraft now), the utility pops out the first 2 panels, then stops with an error message saying that "Unable to popout Panel number 2. Please check..."

It's just popped out Panel 2 and for some reason stops the popout process completly.

One of the aircraft has 4 panels (PMDG 737) and another just 2 (MIlviz Porter).

I've tried deleting the profile and re-learning but the same thing happens. The Popout Panel Manager isn't blocking the screens so I don't know what might be causing this.

Many thanks

Warwick

**Comment by FlyingCatPro** [comment] 2022-12-07 09:28
I'm having exactly the same problem, but with the FFX HondaJet. I can only pop out a single panel. If I try and pop out more than than one, to another monitor, it also stops with an error message stating "Unable to popout Panel number 2. Please check...".

I have tried reinstalling the latest version and also going back to a previous version but still get the same error message.

I use MSFS Popout Panel Manager in conjunction with spacedesk Viewer in order to view it on a second monitor. 

It was working fine until the latest version of Popout Panel Manager.

**Comment by hawkeye-stan** [comment] 2022-12-07 16:05
I'm not able to reproduce your issue and it maybe because I'm an AMD GPU. Other users who were also encountering this issue have it resolved by turning off Nvidia GeForce experience filter. Here is their post on flightsimulator.com forum.

------------------------------------------------------------------------------------------------
PaulFMcG
The issue regarding the 2nd panel not popping out correctly has been Solved.
Turns out this was happening due to Nvidia Geforce Experience filters being turned on. (ALT+F3)

KCPilot8838
Thank you very much… this solved the problem for me. It was driving me crazy, so started scrolling through this thread and found your post!
------------------------------------------------------------------------------------------------

Hope this helps. If not, I'm at a lost since it seems to start happening recently and no matter what I try, I am not able to replicate the issue with both v3.4.4 and v3.4.5.

Stanley

**Comment by FlyingCatPro** [comment] 2022-12-07 18:50
Hi Stanley,

Thanks for the prompt reply and excellent support!

You were spot-on. It was the offending Nvidia Geforce Experience filters causing the problem. After disabling this function all is back to normal and I can pop-out more than just a single panel.

Will there be a future fix for this issue?

It's not a big issue but would be useful to be able to utilise the Nvidia filters.

Thanks for an excellent product and support.

Frank


________________________________

**Comment by Maarp68** [comment] 2022-12-07 20:14
This makes a lot of sense, I only just started using GEForce filters and that's when I met the problem.

I'm pretty sure that you can assign a Filter Off/On event to a button which should then make it easy to turn them off, Pop out and then turn them back on again.

I think more people are using the filters now after watching FlyBy Sim's excellent graphics settings videos. I know that applies to me!

Cheers all

Warwick

**Comment by FlyingCatPro** [comment] 2022-12-07 23:15
Thanks for the 'heads-up' on FlyBy Sims's videos Warwick. I hadn't come across him so will definitely check his stuff out.

Cheers,

Frank.

**Comment by hawkeye-stan** [comment] 2022-12-08 03:06
I will do some investigation into how geforce filter operates technically and try my best to figure out a way to temporarily disable the filter during pop out. No guarantee I will be able to do it since I will be coding blind and will not have a way to test it since I have an older AMD GPU. Currently, I am trying to save up the budget for a new Nvidia 4000 series but it so expensive and not readily available. I don’t think I will have my hands on one until later next year and if the new AMD card that is coming out is any good,  I may not get an Nvidia at all. 

Anyway, I am wondering why the filter is blocking the mouse click action in my code during the pop out process? Weird!

Stanley

**Comment by FlyingCatPro** [comment] 2022-12-08 07:37
Thanks Stanley.

If you would like me to test, please let me know - I am more than willing to do so.

Nvidia 4090s are as rare as hens' teeth in the UK as well and extremely expensive. I'll be holding off until at least late spring (May/June) before upgrading to a 13th generation system. I've been saving monthly for the last 10 years for the new system and have now built up more than enough for a premium system.

Please don't hesitate to contact me if I can assist in any testing that may help you out.

Cheers,

Frank


________________________________

**Comment by Maarp68** [comment] 2022-12-09 02:58
Can confirm that you can easily assign a keyboard shortcut to turn the GEForce Filters on and off which means that all you have to do is turn them off, run Popout Manager, pop out and then turn them back on.

Works a treat!

Cheers all 

Warwick

**Comment by FlyingCatPro** [comment] 2022-12-09 07:51
Hi Warwick,

Good to see you managed to get it to work.

Could you kindly expand on this if possible and explain the steps in your process and how you assign a keyboard shortcut to turn on/off the filters.

Many thanks.

Cheers,

Frank

________________________________

**Comment by Maarp68** [comment] 2022-12-09 18:42
G'day Frank,

I just opened the GE Force control panel, clicked on Settings and there is an option to assign keyboard commands to Filters (and other things). I just picked something that I didn't think MSFS was using (Shift-Alt-7 from memory) and assigned that to Turn Filters Off/On.

Just map that to a button or switch and you can easily turn Filters off, run Popout and then turn Filters back on. You don't even have to map this to a button if you're happy pressing the keys you assigned.

Cheers mate

Warwick

**Comment by FlyingCatPro** [comment] 2022-12-10 06:41
Hi Warwick,

Thanks.

I eventually managed to get it work after some confusion trying to find the Settings.

I initially couldn't find the Settings in 'GE Force control panel' but finally discovered them in 'GeForce Experience'.

Cheers,

Frank

________________________________

**Comment by winternet-studio** [comment] 2023-02-15 09:49
We are talking about disabling Photo mode / Game filter in the Settings of the in-game overlay, right? That doesn't work for me though. But maybe I'm experiencing a different problem. The pop out process does open both panels I have selected, but then I see it clicks the X on the second one and then complains that it couldn't open it!! 🤣

**Closed** 2023-05-06 04:11 UTC
